name: beginners-luck
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/beginners-luck
extra-source-files:
- README.md
ghc-options:
  -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
default-extensions:
- FlexibleContexts
dependencies:
- base >=4.7 && <5
- Chart >=1.8.2
- Chart-diagrams >=1.8.2
- coinbase-exchange
- http-client
- http-client-tls
- streaming
- time
- mtl
library:
  source-dirs: src
executables:
  beginners-luck-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beginners-luck
tests:
  beginners-luck-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beginners-luck
    - tasty
    - tasty-hunit
